# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [1]:
sum=0
for i in range(1,100):
    if i%2==0:
        sum=sum-i
    else:
        sum=sum+i
sum 

50

50


1.3  将字符串 s="yoyo" 转换成列表

In [2]:
s = "yoyo"
new_list = list(s)
print(new_list)

['y', 'o', 'y', 'o']


# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

In [3]:
for i in range(1,100)[2::3][-10:]:
    print (i )

72
75
78
81
84
87
90
93
96
99


2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [13]:
import pandas as pd
import numpy as np
import talib as ta
data = pd.read_excel('sz50.xlsx',sheet_name='600029.XSHG')
close = data.close
np_close = np.array(close)
ema = ta.EMA(np_close,10)
ema[-5:]

array([15.08227205, 15.2564044 , 15.44433088, 15.72172526, 15.96322976])

<class 'numpy.ndarray'>
[ 15.08227205  15.2564044   15.44433088  15.72172526  15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [16]:
import warnings
warnings.filterwarnings('ignore')
from datetime import datetime
import pandas as pd
symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('sz50.xlsx',sheetname=s, index_col='datetime')
    data_dict[s] = data.loc[:]
PN = pd.Panel(data_dict)
print(PN)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [41]:
ndim = PN.transpose(2,1,0).to_frame()
ndim['close'].tail(20)

datetime             minor      
2017-11-10 15:00:00  600050.XSHG      9.97
                     601318.XSHG    156.53
2017-11-13 15:00:00  600029.XSHG     15.35
                     600050.XSHG      9.96
                     601318.XSHG    157.12
2017-11-14 15:00:00  600029.XSHG     16.00
                     600050.XSHG      9.49
                     601318.XSHG    157.72
2017-11-15 15:00:00  600029.XSHG     16.04
                     600050.XSHG      9.68
                     601318.XSHG    154.99
2017-11-16 15:00:00  600029.XSHG     16.29
                     600050.XSHG      9.61
                     601318.XSHG    163.52
2017-11-17 15:00:00  600029.XSHG     16.97
                     600050.XSHG      9.63
                     601318.XSHG    168.58
2017-11-20 15:00:00  600029.XSHG     17.05
                     600050.XSHG      9.80
                     601318.XSHG    169.57
Name: close, dtype: float64

3.5 建立一个5*5的矩阵，值从0到24

In [44]:
matrix = np.array([range(25)])
matrix.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])